### PR TITLE
fix adobe login plugin, when authorized user does not have permissions

### PR DESCRIPTION
**Pull request by kononenkoAnton**
## Description
Fix adobe login plugin case, when authorized user does not have permissions to watch video
[Monday ticket](add your monday ticket url here)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

### CODE REVIEW

**Review by inckie — APPROVED** [review]

**Comment by ranmeirman** [comment]
@inckie btw, on Android if get authorization fails it still shows success

**Comment by inckie** [comment]
@ranmeirman IIRC its ok, it comes from some check that we need to ask library to login first (init), then it will do useful part

**Comment by ranmeirman** [comment]
So maybe this should be also the fix on iOS? Because iOS fails the flow with an error

**Comment by inckie** [comment]
Need to check how exactly it works, I do not remember clearly now, it has a bit twisted logic.
If it works (so we get access to items when we should, and error when we do not), I'd leave it as it is for now.
Then its better to rewrite the plugin, we can delete most of the native code and just route events from adobe flow state machine to react, where we can just write strategy-pattern style handlers for these events to handle logic, and also replace list with general content screen.

**Pull request merged**
